### ISSUE TITLE
Grid setting not saved in json files

### ISSUE THREAD

**Issue by dorrington** [ricktu288/ray-optics#103]
Hi.

Is there any specific reason why the Grid, Snap To Grid, and Lock Objects setting shouldn't be saved in the json files?

I have this working on my local copy (backwards compatible), so am happy to submit the changes if this is a desirable feature.

Any thoughts?

Cheers,
  Adrian.

**Comment by ricktu288** [comment]
I just checked the history and found that this behavior was already there when I first added the "export to JSON" feature in 2011, a long time before I made this project available on GitHub. I forgot what I was thinking about at that time, and I didn't think of it since that.

As for the current version, yes, saving those in the JSON file is a desirable feature. Please submit that.
