### ISSUE TITLE
Colour filters

### ISSUE THREAD

**Issue by gbonfi** [ricktu288/ray-optics#106]
Hello, and thanks for the great app.

There is a missing option for making a proper filter. Could the blocker be made to block just one wavelength? (or vice-versa letting through only one)

Simulating an RGB filter would be immediate without having to manage reflections from mirror or beam splitters.

**Comment by ricktu288** [comment]
@gljames24 Can you work on this one? Since the dichroic filter is created by you.

**Comment by gljames24** [comment]
So just add the dichroic filter feature to the blocker? I can work on that later next week as I'm on a trip right now, but it shouldn't be too hard to get working.

**Comment by gljames24** [comment]
@ricktu288 I moved wavelength interaction and the dichroic property box to the simulator.js so I could invoke them from any object. With the blocker, it isn't actually a dichroic anymore, but rather the more generally an optical filter which should probably be what the user sees as a setting. Also instead of the filter option, it should probably just be named "invert" as that is what it is doing. I can add those to the locales and submit a pull request if you think that sounds good.

**Comment by ricktu288** [comment]
Sounds good. Please use "反向" for zh-TW and zh-CN of "invert".

**Comment by gljames24** [comment]
@ricktu288 Sorry this took so long. Let me know if there is anything you want changed? #108

**Comment by ricktu288** [comment]
Thanks. I changed the appearance to match the wavelength when filter is on (it may somewhat be misleading since when "invert" is off the actual appearance when there is a blacklight should be more like the complementary color, but the appearance of other components in this app do not have a common physical meaning anyway), and also show a checkbox of "filter" instead of "show advanced options" in the selected object bar.
