### ISSUE TITLE
[Feature request] Add control to adjust observer's size

### ISSUE THREAD

**Issue by DIYer22** [ricktu288/ray-optics#111]
Thank you for the great work. I think the observer's should be changeable.

**Comment by ricktu288** [comment]
For now, you may change the observer's size by either of the following:
1. Open the developer console and type `observer.r = 50; draw();`. Replace 50 with your desired radius in pixels.
2. Switch to "Seen by Observer" and save the scene to a JSON file. Find the following code
```js
  "observer": {
    "type": 5,
    "c": {
      "type": 1,
      "x": 100, /*Some coordinates*/
      "y": 100, /*Some coordinates*/
      "exist": true
    },
    "r": 20,
    "exist": true
  },
```
and replace 20 by your desired radius in pixels.

As for the feature request, I think maybe a good approach is to make observer an object so that the radius can be changed with a slider when selected, and it can also be duplicated to have multiple observers. But that requires a lot of code change and is not expected to be implemented in the near future.

**Comment by DIYer22** [comment]
![image](https://github.com/ricktu288/ray-optics/assets/10448025/44698aa7-5d70-4095-bb92-f5ad540ac7b9)
It works! thank you so much!

**Comment by ricktu288** [comment]
I will keep this open because a proper control in the UI itself for this functionality is still desired.

**Comment by ricktu288** [comment]
The "Observer size" option is now available in Settings.
