### ISSUE TITLE
Metric units

### ISSUE THREAD

**Issue by sajmons** [ricktu288/ray-optics#39]
Is it possible to set ruller units to milimeters or centimeters? If not, can it be done?

**Comment by ricktu288** [comment]
In this web app, all the length scales (coordinates, ruler, focal length, etc.) are in the same arbitrary unit, which corresponds to the CSS pixels when the zoom percentage is 100. Since the wavelength is assumed to be infinitesimal in ray optics, the absolute length scale of the optical system is irrelevant in the simulation. You can freely interpret that unit to be millimeters, kilometers, or whatever. The simulation result will always be the same.

Although It is possible to use absolute units (cm, mm, etc.) in webpages, the W3C does not recommend this usage, since the length may be inaccurate on computer screens. See https://www.w3.org/Style/Examples/007/units.en.html.
