### ISSUE TITLE
Menus and Help Button?

### ISSUE THREAD

**Issue by RainerHeintzmann** [ricktu288/ray-optics#40]
This seems to be a great tool. However, it seems that for me (Windows 10, Chrome 
Version 98.0.4758.102 (Official Build) (64-bit) ) the `Help` button and the menus `Examples`, `Mirrors`, `Glasses` are not working.
They have a little folded corner visible indicating that they are probably menus, but clicking on them with any of my three mouse buttons in any single or double click combination I tried seems to have no effect.

Any idea what I might be doing wrong?
I also tried cloning and running it locally, but the effect is the same.
Running it on InternetExplorer is messed up:
![image](https://user-images.githubusercontent.com/7559915/156225417-d6f540d6-b5c8-4f3d-9334-7462ece5a603.png)

On Microsoft Edge, I get similar results as on Chrome. Yet, the menus and `Help` button are also not working.

**Comment by j3soon** [comment]
Tried it on Windows 10 Chrome Version `98.0.4758.102 (Official Build) (64-bit)` and Edge Version `98.0.1108.62 (Official build) (64-bit)`. Cannot reproduce the error.

Can you post a screenshot of the console logs in the console window? (`Ctrl+Shift+I > Console`)

Did the error persist in Incognito/Private Mode?

**Comment by RainerHeintzmann** [comment]
Thanks for trying it out. I tried in the Incognito mode and both the online and local versions have the same problem.
The console yields:
![image](https://user-images.githubusercontent.com/7559915/156311669-4220211f-bdec-4156-a4fa-63a7303498e8.png)
in the local version and
![image](https://user-images.githubusercontent.com/7559915/156311867-87fcf42d-dd44-44e2-9d71-7898b1022ba5.png)
in the online version. (Both on Chrome),

**Comment by RainerHeintzmann** [comment]
.. these problems seem to be on startup and no more error are reported on hover or click. But no menus are visible.

**Comment by RainerHeintzmann** [comment]
Thats interesting. In fact I cannot access that site.
![image](https://user-images.githubusercontent.com/7559915/156354368-d26e1637-d2c0-4327-8df7-d9fcc98455b3.png)

**Comment by j3soon** [comment]
I think it's due to some errors in your internet connection or your machine's DNS cache. You may try out some potential solutions:
- Flush your DNS Cache
  Follow the instructions in [this post](https://support.pearson.com/getsupport/s/article/Reset-an-Internet-Connection-Flush-DNS) and reopen ray-optics in Incognito mode.
- Download ray-optics to local file system, change the URL in [Line 380 of `simulator/index.html`](https://github.com/ricktu288/ray-optics/blob/3d3f97f84f48893f3ed5667752012fde0bd32195/simulator/index.html#L380) to another CDN you have access to (maybe `https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js`) and open this HTML file locally. If the console shows other `ERR_CONNECTION_RESET` errors as shown in the image below, you may need to resolve the connection issue for each dependency. (Line 380-383 in `simulator/index.html`)
  ![jquery](https://user-images.githubusercontent.com/20457146/156357894-e9d946d1-f619-464d-847b-25fd8f0f6e34.png)
- Try out ray-optics on another machine

**Comment by RainerHeintzmann** [comment]
Thanks a lot for the hints!
After flushing the DNS cache (which needed several restarts) in incognito mode nothing changed.
In the normal mode I get an additional warning:
![image](https://user-images.githubusercontent.com/7559915/156365642-8275445b-4f6e-40cb-b97f-e345eea672a5.png)

However, changing line `380 in index.html` did the trick and now everything sees to work fine.
Maybe one can somehow put this as an alternative? No idea why I cannot access the other site. Possibly the virus scanners are preventing this? I am using a university computer, but from my home. 

By the way. We are interested in possibly using your fantastic tool as a basis for a tutorial on optical alignment. A student may contact you soon. I think a first step would be some properties of restricting the ability of users to influence all properties of the various elements. Ultimately we are also thinking of upgrading the raytracing to 3D but keeping the view(s) 2D. But anyway, this is a different discussion.
