### ISSUE TITLE
Counting number of reflections [Feature Request]

### ISSUE THREAD

**Issue by lorepieri8** [ricktu288/ray-optics#46]
It would be nice to have stats on the number of reflections the rays do on any surface, e.g. on a spherical mirror.

**Comment by ricktu288** [comment]
Actually, there is a `<span id="status">` that shows the total numbers of rays. It is hidden and is only for debugging purpose (it can be viewed with the web developer tool.)

However, if refractors are present, the number is meaningless since the true number of internal reflections is always infinite.

**Comment by ricktu288** [comment]
Now you can turn on "Show status box" in Settings to show the total number of ray segments, from which certain kinds of "number of reflections" can be inferred.
