### ISSUE TITLE
Brightness in ColorMode is Broken in All Light Sources but the Ray

### ISSUE THREAD

**Issue by gljames24** [ricktu288/ray-optics#86]
Unlike the basic ray, the brightness scale in all other light sources only works between 0 to ~0.16.
It can be seen in the resulting beam between these to sets of light sources. Each set of light sources has the exact same brightness value between hues.
![image](https://user-images.githubusercontent.com/22029083/214364796-14a9da34-1a89-4fc7-88b9-c1a745a377ba.png)

**Comment by ricktu288** [comment]
Set "ray density" to a higher value will solve the problem. The alpha value of the rays saturate at low density.

**Comment by ricktu288** [comment]
One way to solve all the color saturation problems in this app is to use floating point color buffer. I think WebGL has such feature but I don't know how to use it.

**Comment by gljames24** [comment]
Yeah that seems to have fixed it:
![image](https://user-images.githubusercontent.com/22029083/214404700-aa63f526-3fd2-47b5-9fc4-15cd3362968e.png)

I not familar with WebGL so I'm not sure if I can help on this one, but I'll try to tinker around with it.

**Comment by ricktu288** [comment]
See also #14. But I don't know whether Tantalum has the same issue.

**Comment by ricktu288** [comment]
I was mistaken. This issue is in fact unrelated to the more fundamental issue (saturation of color buffer) I was talking about. Instead, this issue is simply solved by removing the `Math.min` in
```
ray1.brightness_s = Math.min(obj.p / getRayDensity() * brightness_factor, 1) * 0.5;
```

However, since this causes compatibility problems. I will fixed it later.

**Comment by ricktu288** [comment]
The behavior of the "brightness" is designed to be equal to the alpha channel of the ray at the ray density where the distance between consecutive rays equals the width of the ray (1 css pixel at 100% zoom). Since the alpha value is also used as the intensity when dealing with the glass surface and also for the detector tool, the design here is that the alpha value scales inversely with the ray density (so that the ray density behaves as a quality-performance tradeoff for continuous ray simulation).

However, when the ray density is too low such that the alpha value is greater than one, that value is truncated to one.

The problem is that, if the truncation is removed, then when the user shines the ray on a glass surface, the intensity will look unnatural, since the refracted rays will have an apparent alpha value close to the incoming ray.

One way to solve this is to set the default value of the brightness to ~0.16 instead of 0.5. However, then if a user increases the ray density to a high value without understanding the brightness behavior, the rays will become very dim, which is not a good experience for new users.

Another way is to keep the default brightness to be 0.5 but set the default value of the ray density to a high value. However, this is also not a good experience as the user may turn the ray density down. Note that the majority of the use cases of this app require low ray density.

A compromised solution is to scale the intensity in a piecewise manner with the ray density. The most natural way to do this is that when the distance between the rays is larger than the width of the ray, the intensity equals the brightness; otherwise, scales inversely with ray density. The problem with this is that the default behavior of the overall alpha should be ~1 for ray density and <1 (~0.5) for high ray density. Considering this, the minimal solution will be:

 - When the distance between the rays is larger than the *twice the* width of the ray, the intensity equals the brightness
 - Otherwise, the intensity scales inversely with ray density.

I don't know if such a complication is necessary.

Or maybe we should just add a popup description of the "brightness" field to clarify the current behavior and possibly warn the user if trying to do color mixtures at low ray density.

**Comment by ricktu288** [comment]
An info popup has been added next to "Brightness" for this behavior.

**Comment by ricktu288** [comment]
> One way to solve all the color saturation problems in this app is to use floating point color buffer. I think WebGL has such feature but I don't know how to use it.

This is now implemented.
